# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-02 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notes',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
