# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-03 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_user_notes_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notes',
            name='original_note_id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
